export const demoProducts = [
  {
    _id: "1",
    title: "Classic White Tee",
    description: "Premium Heavyweight Cotton",
    basePrice: 28,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "classic-white-tee",
  },
  {
    _id: "2",
    title: "Black Oversized Tee",
    description: "Premium Heavyweight Cotton",
    basePrice: 34,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "premium-oversized-hoodie",
  },
  {
    _id: "3",
    title: "Navy Executive Polo",
    description: "Pique Organic Cotton",
    basePrice: 42,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "navy-executive-polo",
  },
  {
    _id: "4",
    title: "Sustainable Gray Hoodie",
    description: "Recycled Polyester Blend",
    basePrice: 56,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "sustainable-gray-hoodie",
  },
  {
    _id: "5",
    title: "Essential Tank Top",
    description: "Lightweight Sport Mesh",
    basePrice: 22,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "essential-tank-top",
  },
  {
    _id: "6",
    title: "Premium Crewneck",
    description: "French Terry Finish",
    basePrice: 48,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "premium-crewneck",
  },
  {
    _id: "7",
    title: "Vintage Wash Tee",
    description: "Pre-Shrunk Garment Dye",
    basePrice: 32,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "vintage-wash-tee",
  },
  {
    _id: "8",
    title: "Raglan Baseball Tee",
    description: "Contrast Sleeve Cotton",
    basePrice: 26,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "raglan-baseball-tee",
  },
  {
    _id: "9",
    title: "Heather Gray V-Neck",
    description: "Soft Touch Finish",
    basePrice: 24,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "heather-gray-vneck",
  },
  {
    _id: "10",
    title: "Athletic Performance Shirt",
    description: "Moisture Wicking Tech",
    basePrice: 38,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "athletic-performance-shirt",
  },
  {
    _id: "11",
    title: "Classic Polo Shirt",
    description: "Premium Pique Fabric",
    basePrice: 44,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "classic-polo-shirt",
  },
  {
    _id: "12",
    title: "Comfortable Sweatshirt",
    description: "Cozy Cotton Blend",
    basePrice: 52,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "comfortable-sweatshirt",
  },
  {
    _id: "13",
    title: "Striped Cotton Tee",
    description: "Classic Striped Pattern",
    basePrice: 30,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "striped-cotton-tee",
  },
  {
    _id: "14",
    title: "Long Sleeve Henley",
    description: "Button Neck Design",
    basePrice: 36,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "long-sleeve-henley",
  },
  {
    _id: "15",
    title: "Lightweight Summer Shirt",
    description: "Breathable Fabric",
    basePrice: 28,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "lightweight-summer-shirt",
  },
  {
    _id: "16",
    title: "Premium Zip Hoodie",
    description: "Full Zip Closure",
    basePrice: 62,
    image: "/images/home/Menclothing.png",
    images: ["/images/home/Menclothing.png"],
    slug: "premium-zip-hoodie",
  },
];
